export interface Mutation {
  id: string;
  why: string;
  file: string;
  find: string;
  replace: string;
  suite: "bun" | "browser";
  expect: string;
}

// Browser-only defects are deliberately not in this corpus yet: the page.url() epoch leak and
// the epoch:0 counter need suite: "browser" wiring that this pass does not exercise.
export const MUTATIONS: Mutation[] = [
  {
    id: "publish-validation-unwired",
    why: "2d29a66 — deleting the call left 47 Bun + 22 browser green.",
    file: "src/capture/record.ts",
    find: "if (!staged.ok) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "captureHar refuses to publish when a HAR attachment corrupts a staged sidecar",
  },
  {
    id: "epoch-shape-rule-gone",
    why: "Issue #47 — removing the document-epoch shape check let URL-shaped and short epochs pass.",
    file: "src/capture/checkpoints.ts",
    find: "^epoch:[0-9A-Za-z_-]{16,}$",
    replace: ".+",
    suite: "bun",
    expect: "rejects a documentEpoch that carries the captured page URL",
  },
  {
    id: "epoch-binding-unchecked",
    why: "89650be — deleting the documentEpoch binding refusal left 61 Bun tests green.",
    file: "src/capture/checkpoints.ts",
    find: "if (binding.documentEpoch !== finalCheckpoint.primaryTarget.documentEpoch) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when the binding names the final checkpoint but a different document epoch",
  },
  {
    id: "checkpoint-artifacts-shape-unchecked",
    why: "Issue #68 — removing the artifacts array guard accepted a checkpoint with scalar artifacts.",
    file: "src/capture/checkpoints.ts",
    find: "if (!Array.isArray(checkpoint.artifacts)) return false;",
    replace: "if (false) return false;",
    suite: "bun",
    expect: "rejects a checkpoint whose artifacts is not an array",
  },
  {
    id: "openedat-binding-unchecked",
    why: "1b71ef2 — deleting the openedAt binding refusal left 61 Bun tests green.",
    file: "src/capture/checkpoints.ts",
    find: "if (binding.openedAt !== finalCheckpoint.openedAt) return { ok: false };",
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "refuses when the binding names the final checkpoint but a different openedAt",
  },
  {
    id: "mid-checkpoint-navigation-allowed",
    why: "Issue #47 — deleting the loaderId change refusal allowed mid-checkpoint navigation.",
    file: "src/capture/record.ts",
    find: "if (loaderIdAtClose !== loaderIdAtOpen) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "captureHar refuses to publish when the primary document changes while the checkpoint was open",
  },
  {
    id: "har-containment-unchecked",
    why: "Issue #47 — removing the HAR containment refusal allowed an association outside staging.",
    file: "src/capture/checkpoints.ts",
    find: "return isStrictlyWithin(resolvedRoot, resolvedPath);",
    replace: "return true;",
    suite: "bun",
    expect: "refuses when the HAR association resolves outside the staging root",
  },
  {
    id: "capabilities-association-required",
    why: "Issue #63 — removing the required run-level capabilities association accepted an unindexed artifact.",
    file: "src/capture/checkpoints.ts",
    find: "if (!isRunAssociation(checkpointsDocument.capabilities)) return { ok: false };",
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects a document missing the run-level capabilities association",
  },
  {
    id: "capabilities-file-required",
    why: "Issue #63 — removing the capabilities staged-file check accepted a missing or non-file artifact.",
    file: "src/capture/checkpoints.ts",
    find: "if (!(await isStagedRegularFile(stagingRoot, stagedDocument.capabilities as RunAssociation))) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when capabilities.json resolves outside the staging root",
  },
  {
    id: "capabilities-document-validated",
    why: "Issue #63 — removing capabilities document validation accepted invalid JSON and invalid schema documents.",
    file: "src/capture/checkpoints.ts",
    find: "if (capabilitiesDoc === undefined || !validateCapabilities(capabilitiesDoc).ok) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when capabilities.json has an unsupported schema version",
  },
  {
    id: "capabilities-flag-values-validated",
    why: "Issue #63 — removing tri-state value validation accepted values outside the contract.",
    file: "src/capture/checkpoints.ts",
    find: "if (flag in flags && !isCapabilityValue(flags[flag])) return { ok: false };",
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects capabilities with a value outside the tri-state contract",
  },
  {
    id: "capabilities-flags-required",
    why: "Issue #63 — removing the required-flag check accepted incomplete capability evidence.",
    file: "src/capture/checkpoints.ts",
    find: "if (!(flag in flags)) return { ok: false };",
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects capabilities missing one of the four flags",
  },
  {
    id: "capability-service-worker-detection",
    why: "Issue #64 — suppressing the ServiceWorker registration observation made a true dependency look absent.",
    file: "src/capture/record.ts",
    find: "serviceWorkerDependent = true;",
    replace: "serviceWorkerDependent = false;",
    suite: "browser",
    expect: "publishes true capabilities for the capability fixture",
  },
  {
    id: "capability-websocket-detection",
    why: "Issue #64 — suppressing the live WebSocket observation made a refused socket look absent.",
    file: "src/capture/record.ts",
    find: "webSocketDependent = true;",
    replace: "webSocketDependent = false;",
    suite: "browser",
    expect: "publishes true capabilities for the capability fixture",
  },
  {
    id: "capability-closed-shadow-root-detection",
    why: "Issue #64 — replacing the pierced DOM result with false hid a closed shadow root.",
    file: "src/capture/record.ts",
    find: "const closedShadowRootPresent = hasClosedShadowRoot(domDocument.root);",
    replace: "const closedShadowRootPresent = false;",
    suite: "browser",
    expect: "publishes true capabilities for the capability fixture",
  },
  {
    id: "capability-sourcemap-detection",
    why: "Issue #64 — replacing sourcemap declaration detection with false hid declared maps.",
    file: "src/capture/record.ts",
    find: "sourcemapDeclared: sourcemapDeclared ? true : scriptBodyUnreadable ? \"undetermined\" : false,",
    replace: "sourcemapDeclared: false,",
    suite: "browser",
    expect: "publishes true capabilities for the capability fixture",
  },
  {
    id: "sourcemap-post-sweep-fetch",
    why: "Issue #75 — skipping discovered map fetches omitted the map declared by a sweep-loaded script.",
    file: "src/capture/record.ts",
    find: "[...discoveredMapUrls].map((url) => context.request.get(url).catch(() => undefined)),",
    replace: "[...new Set<string>()].map((url) => context.request.get(url).catch(() => undefined)),",
    suite: "browser",
    expect: "publishes true capabilities for the capability fixture",
  },
  {
    id: "sourcemap-declaration-before-url-resolution",
    why: "Issue #75 — tying declaration evidence to a resolved URL misclassified malformed declarations.",
    file: "src/capture/record.ts",
    find: "sourcemapDeclared = true;",
    replace: "sourcemapDeclared = discoveredMapUrls.size > 0;",
    suite: "bun",
    expect: "publishes a sourcemap declaration whose URL cannot be resolved",
  },
  {
    id: "capability-observation-boundary",
    why: "Issue #75 — leaving dependency observation live let shutdown events cross the published boundary.",
    file: "src/capture/record.ts",
    find: "observingDependencies = false;",
    replace: "observingDependencies = true;",
    suite: "bun",
    expect: "ignores dependency events delivered after capabilities are observed",
  },
  {
    id: "target-creation-observation-boundary",
    why: "#117 review — the discovery listeners shipped without the boundary the capability flags have, so a target Chromium reported during context.close() was published as if the page had opened it.",
    file: "src/capture/record.ts",
    find: `if (!observingDependencies) return;
          const info = (payload as { targetInfo?: CdpTargetPayload }).targetInfo;`,
    replace: "const info = (payload as { targetInfo?: CdpTargetPayload }).targetInfo;",
    suite: "bun",
    expect: "stops recording targets once the observation window closes",
  },
  {
    id: "target-destruction-observation-boundary",
    why: "#117 review — same boundary on the destroy path: closing the context destroys every target it owns, and an unguarded handler stamps closedAt for our own teardown.",
    file: "src/capture/record.ts",
    find: `if (!observingDependencies) return;
          const targetId = (payload as { targetId?: unknown }).targetId;`,
    replace: "const targetId = (payload as { targetId?: unknown }).targetId;",
    suite: "bun",
    expect: "does not close a target on a destroy that arrives after the observation window",
  },
  {
    id: "snapshot-opener-asserted-unverified",
    why: "#117 deliverable 2 — carrying a snapshot's openerId verbatim aborts the whole capture, because validateTargets refuses a dangling reference and Target.getTargets reports targets whose opener has already closed.",
    file: "src/capture/targets.ts",
    find: "targetEntryFromCreated(openerRecorded ? info : { ...info, openerId: undefined }, openedAt),",
    replace: "targetEntryFromCreated(info, openedAt),",
    suite: "bun",
    expect: "keeps a snapshot target whose opener the run never recorded",
  },
  {
    id: "snapshot-drain-missing",
    why: "#117 deliverable 2 — without the drain, a target the snapshot proves is gone keeps no closedAt, because the listener guard filters on delivery time and the destroy may never be observed.",
    file: "src/capture/targets.ts",
    find: "entry.closedAt === undefined && drainable.has(entry.targetId) && !live.has(entry.targetId),",
    replace: "false,",
    suite: "bun",
    expect: "closes a target the snapshot proves is gone",
  },
  {
    id: "snapshot-drain-ignores-inflight-creation",
    why: "#117 review — Target.getTargets is not atomic: Chromium enumerates, then the response travels back. Without restricting the drain to what was recorded before the request, a target created in that window is stamped closed while it is still alive.",
    file: "src/capture/targets.ts",
    find: "entry.closedAt === undefined && drainable.has(entry.targetId) && !live.has(entry.targetId),",
    replace: "entry.closedAt === undefined && !live.has(entry.targetId),",
    suite: "bun",
    expect: "does not close a target created while the snapshot was in flight",
  },
  {
    id: "fingerprint-key-gates-on-ordinal-and-text",
    why: "Issue #20, fixed in 44e2671 — ordinal and text hash were equality components of the bucket key, so one node inserted above a target made an element with a unique stable attribute unmatchable. It was reported `missing` and `replayOnly` at once.",
    file: "src/identity/fingerprint.ts",
    find: 'return [el.frameKey, el.tag, attrs].join("|");',
    replace: 'return [el.frameKey, el.tag, attrs, el.siblingOrdinal, el.textHash ?? ""].join("|");',
    suite: "bun",
    expect: "one unrelated node inserted above does not lose an element with a unique attribute",
  },
  {
    id: "request-normalization-association-required",
    why: "Issue #86 — dropping the required requestNormalization run association from checkpoints validation let an archive without a policy pass the manifest guard.",
    file: "src/capture/checkpoints.ts",
    find: 'if (!isRunAssociation(checkpointsDocument.requestNormalization)) return { ok: false };',
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects a document missing the run-level request-normalization association",
  },
  {
    id: "request-normalization-staged-file-required",
    why: "Issue #86 — dropping the staged regular-file check let an archive publish a policy that escapes the root through a symlink while remaining valid JSON.",
    file: "src/capture/checkpoints.ts",
    find: '!(await isStagedRegularFile(stagingRoot, stagedDocument.requestNormalization as RunAssociation))',
    replace: "false",
    suite: "bun",
    expect: "refuses when request-normalization.json resolves outside the staging root",
  },
  {
    id: "request-normalization-schema-unchecked",
    why: "Issue #86 — dropping the policy schema validation let a malformed or non-empty-key policy be published.",
    file: "src/capture/checkpoints.ts",
    find: "if (requestNormalizationDoc === undefined || !validateRequestNormalization(requestNormalizationDoc).ok) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when request-normalization.json is invalid JSON",
  },
  {
    id: "request-normalization-producer-ambiguity-unchecked",
    why: "Issue #91 — dropping the producer-side ambiguity check let a capture publish an archive whose policy collapses two distinct requests into one normalized match.",
    file: "src/capture/record.ts",
    find: 'const ambiguous = findAmbiguousNormalizedRequests(harEntries, volatileKeys);',
    replace: "const ambiguous: string[] = [];",
    suite: "bun",
    expect: "captureHar refuses when the policy collapses two distinct archived requests",
  },
  {
    id: "request-normalization-staged-ambiguity-unchecked",
    why: "Issue #91 — dropping the staged re-check let a tampered policy collapse distinct archived requests bypass the producer guard.",
    file: "src/capture/checkpoints.ts",
    find: "if (findAmbiguousNormalizedRequests(harEntries, volatileKeys as string[]).length > 0) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when the policy collapses distinct archived requests (ambiguity)",
  },
  {
    id: "commit-association-required",
    why: "Issue #103 — dropping the required commit run association from checkpoints validation let an archive publish without a commit marker.",
    file: "src/capture/checkpoints.ts",
    find: 'if (!isRunAssociation(checkpointsDocument.commit)) return { ok: false };',
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects a document missing the run-level commit association",
  },
  {
    id: "commit-marker-not-written",
    why: "Issue #103 — dropping the commit write let a capture publish without a marker a reader could verify against.",
    file: "src/capture/record.ts",
    find: "const commit = await buildCommit(stagingRoot, finalCheckpoint.checkpointId);",
    replace: "const commit = { schemaVersion: 0, producer: { name: \"x\", version: \"0\" }, createdAt: 0, artifacts: [], checkpointId: \"\" };",
    suite: "bun",
    expect: "captureHar publishes a commit marker that verifies the archive bytes",
  },
  {
    id: "termination-association-required",
    why: "Issue #104 — dropping the required termination run association from checkpoints validation let an archive publish without recording why capture stopped.",
    file: "src/capture/checkpoints.ts",
    find: 'if (!isRunAssociation(checkpointsDocument.termination)) return { ok: false };',
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects a document missing the run-level termination association",
  },
  {
    id: "termination-not-recorded",
    why: "Issue #104 — dropping the termination write let a capture publish without a record of its outcome, making a truncated capture indistinguishable from a complete one.",
    file: "src/capture/record.ts",
    find: "const terminationDecision = evaluateBudget(sweepBudgets, terminationStats);",
    replace: "const terminationDecision = { stop: false } as const;",
    suite: "bun",
    expect: "captureHar records budget-exceeded when the wall-clock cap is crossed",
  },
  {
    id: "termination-staged-file-required",
    why: "Issue #104 follow-up — dropping the termination staged regular-file check let a capture publish an archive whose association names a missing or directory termination.json (it is written before validation, unlike commit, so it can and must be checked here).",
    file: "src/capture/checkpoints.ts",
    find: 'if (!(await isStagedRegularFile(stagingRoot, stagedDocument.termination as RunAssociation))) {',
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when termination.json is missing",
  },
  {
    id: "targets-association-required",
    why: "Issue #117 — removing the required run-level targets association accepted an archive that never indexed the inventory.",
    file: "src/capture/checkpoints.ts",
    find: "if (!isRunAssociation(checkpointsDocument.targets)) return { ok: false };",
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects a document missing the run-level targets association",
  },
  {
    id: "targets-containment-unchecked",
    why: "Issue #117 — removing the staged-file check let a targets association outside the staging root be read as this run's evidence.",
    file: "src/capture/checkpoints.ts",
    find: "if (!(await isStagedRegularFile(stagingRoot, stagedDocument.targets as RunAssociation))) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when the targets association resolves outside the staging root",
  },
  {
    id: "targets-document-validated",
    why: "Issue #117 — removing inventory validation accepted a malformed inventory and one whose target closed before it opened.",
    file: "src/capture/checkpoints.ts",
    find: "if (targetsDoc === undefined || !validateTargets(targetsDoc).ok) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses a target that closed before it opened",
  },
];
