export interface Mutation {
  id: string;
  why: string;
  file: string;
  find: string;
  replace: string;
  suite: "bun" | "browser";
  expect: string;
}

// Browser-only defects are deliberately not in this corpus yet: the page.url() epoch leak and
// the epoch:0 counter need suite: "browser" wiring that this pass does not exercise.
export const MUTATIONS: Mutation[] = [
  {
    id: "publish-validation-unwired",
    why: "2d29a66 — deleting the call left 47 Bun + 22 browser green.",
    file: "src/capture/record.ts",
    find: "if (!staged.ok) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "captureHar refuses to publish when a HAR attachment corrupts a staged sidecar",
  },
  {
    id: "epoch-shape-rule-gone",
    why: "Issue #47 — removing the document-epoch shape check let URL-shaped and short epochs pass.",
    file: "src/capture/checkpoints.ts",
    find: "^epoch:[0-9A-Za-z_-]{16,}$",
    replace: ".+",
    suite: "bun",
    expect: "rejects a documentEpoch that carries the captured page URL",
  },
  {
    id: "epoch-binding-unchecked",
    why: "89650be — deleting the documentEpoch binding refusal left 61 Bun tests green.",
    file: "src/capture/checkpoints.ts",
    find: "if (binding.documentEpoch !== finalCheckpoint.primaryTarget.documentEpoch) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when the binding names the final checkpoint but a different document epoch",
  },
  {
    id: "checkpoint-artifacts-shape-unchecked",
    why: "Issue #68 — removing the artifacts array guard accepted a checkpoint with scalar artifacts.",
    file: "src/capture/checkpoints.ts",
    find: "if (!Array.isArray(checkpoint.artifacts)) return false;",
    replace: "if (false) return false;",
    suite: "bun",
    expect: "rejects a checkpoint whose artifacts is not an array",
  },
  {
    id: "openedat-binding-unchecked",
    why: "1b71ef2 — deleting the openedAt binding refusal left 61 Bun tests green.",
    file: "src/capture/checkpoints.ts",
    find: "if (binding.openedAt !== finalCheckpoint.openedAt) return { ok: false };",
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "refuses when the binding names the final checkpoint but a different openedAt",
  },
  {
    id: "mid-checkpoint-navigation-allowed",
    why: "Issue #47 — deleting the loaderId change refusal allowed mid-checkpoint navigation.",
    file: "src/capture/record.ts",
    find: "if (loaderIdAtClose !== loaderIdAtOpen) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "captureHar refuses to publish when the primary document changes while the checkpoint was open",
  },
  {
    id: "har-containment-unchecked",
    why: "Issue #47 — removing the HAR containment refusal allowed an association outside staging.",
    file: "src/capture/checkpoints.ts",
    find: "return isStrictlyWithin(resolvedRoot, resolvedPath);",
    replace: "return true;",
    suite: "bun",
    expect: "refuses when the HAR association resolves outside the staging root",
  },
  {
    id: "capabilities-association-required",
    why: "Issue #63 — removing the required run-level capabilities association accepted an unindexed artifact.",
    file: "src/capture/checkpoints.ts",
    find: "if (!isRunAssociation(checkpointsDocument.capabilities)) return { ok: false };",
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects a document missing the run-level capabilities association",
  },
  {
    id: "capabilities-file-required",
    why: "Issue #63 — removing the capabilities staged-file check accepted a missing or non-file artifact.",
    file: "src/capture/checkpoints.ts",
    find: "if (!(await isStagedRegularFile(stagingRoot, stagedDocument.capabilities as RunAssociation))) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when capabilities.json resolves outside the staging root",
  },
  {
    id: "capabilities-document-validated",
    why: "Issue #63 — removing capabilities document validation accepted invalid JSON and invalid schema documents.",
    file: "src/capture/checkpoints.ts",
    find: "if (capabilitiesDoc === undefined || !validateCapabilities(capabilitiesDoc).ok) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when capabilities.json has an unsupported schema version",
  },
  {
    id: "capabilities-flag-values-validated",
    why: "Issue #63 — removing tri-state value validation accepted values outside the contract.",
    file: "src/capture/checkpoints.ts",
    find: "if (flag in flags && !isCapabilityValue(flags[flag])) return { ok: false };",
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects capabilities with a value outside the tri-state contract",
  },
  {
    id: "capabilities-flags-required",
    why: "Issue #63 — removing the required-flag check accepted incomplete capability evidence.",
    file: "src/capture/checkpoints.ts",
    find: "if (!(flag in flags)) return { ok: false };",
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects capabilities missing one of the four flags",
  },
  {
    id: "capability-service-worker-detection",
    why: "Issue #64 — suppressing the ServiceWorker registration observation made a true dependency look absent.",
    file: "src/capture/record.ts",
    find: "serviceWorkerDependent = true;",
    replace: "serviceWorkerDependent = false;",
    suite: "browser",
    expect: "publishes true capabilities for the capability fixture",
  },
  {
    id: "capability-websocket-detection",
    why: "Issue #64 — suppressing the live WebSocket observation made a refused socket look absent.",
    file: "src/capture/record.ts",
    find: "webSocketDependent = true;",
    replace: "webSocketDependent = false;",
    suite: "browser",
    expect: "publishes true capabilities for the capability fixture",
  },
  {
    id: "capability-closed-shadow-root-detection",
    why: "Issue #64 — replacing the pierced DOM result with false hid a closed shadow root.",
    file: "src/capture/record.ts",
    find: "const closedShadowRootPresent = hasClosedShadowRoot(domDocument.root);",
    replace: "const closedShadowRootPresent = false;",
    suite: "browser",
    expect: "publishes true capabilities for the capability fixture",
  },
  {
    id: "capability-sourcemap-detection",
    why: "Issue #64 — replacing sourcemap declaration detection with false hid declared maps.",
    file: "src/capture/record.ts",
    find: "sourcemapDeclared: sourcemapDeclared ? true : scriptBodyUnreadable ? \"undetermined\" : false,",
    replace: "sourcemapDeclared: false,",
    suite: "browser",
    expect: "publishes true capabilities for the capability fixture",
  },
  {
    id: "sourcemap-post-sweep-fetch",
    why: "Issue #75 — skipping discovered map fetches omitted the map declared by a sweep-loaded script.",
    file: "src/capture/record.ts",
    find: "[...discoveredMapUrls].map((url) => context.request.get(url).catch(() => undefined)),",
    replace: "[...new Set<string>()].map((url) => context.request.get(url).catch(() => undefined)),",
    suite: "browser",
    expect: "publishes true capabilities for the capability fixture",
  },
  {
    id: "sourcemap-declaration-before-url-resolution",
    why: "Issue #75 — tying declaration evidence to a resolved URL misclassified malformed declarations.",
    file: "src/capture/record.ts",
    find: "sourcemapDeclared = true;",
    replace: "sourcemapDeclared = discoveredMapUrls.size > 0;",
    suite: "bun",
    expect: "publishes a sourcemap declaration whose URL cannot be resolved",
  },
  {
    id: "capability-observation-boundary",
    why: "Issue #75 — leaving dependency observation live let shutdown events cross the published boundary.",
    file: "src/capture/record.ts",
    find: "observingDependencies = false;",
    replace: "observingDependencies = true;",
    suite: "bun",
    expect: "ignores dependency events delivered after capabilities are observed",
  },
  {
    id: "target-creation-observation-boundary",
    why: "#117 review — the discovery listeners shipped without the boundary the capability flags have, so a target Chromium reported during context.close() was published as if the page had opened it.",
    file: "src/capture/record.ts",
    find: `if (!observingDependencies) return;
          const info = (payload as { targetInfo?: CdpTargetPayload }).targetInfo;`,
    replace: "const info = (payload as { targetInfo?: CdpTargetPayload }).targetInfo;",
    suite: "bun",
    expect: "stops recording targets once the observation window closes",
  },
  {
    id: "target-destruction-observation-boundary",
    why: "#117 review — same boundary on the destroy path: closing the context destroys every target it owns, and an unguarded handler stamps closedAt for our own teardown.",
    file: "src/capture/record.ts",
    find: `if (!observingDependencies) return;
          const targetId = (payload as { targetId?: unknown }).targetId;`,
    replace: "const targetId = (payload as { targetId?: unknown }).targetId;",
    suite: "bun",
    expect: "does not close a target on a destroy that arrives after the observation window",
  },
  {
    id: "snapshot-opener-asserted-unverified",
    why: "#117 deliverable 2 — carrying a snapshot's openerId verbatim aborts the whole capture, because validateTargets refuses a dangling reference and Target.getTargets reports targets whose opener has already closed.",
    file: "src/capture/targets.ts",
    find: "targetEntryFromCreated(openerRecorded ? info : { ...info, openerId: undefined }, openedAt),",
    replace: "targetEntryFromCreated(info, openedAt),",
    suite: "bun",
    expect: "keeps a snapshot target whose opener the run never recorded",
  },
  {
    id: "snapshot-drain-missing",
    why: "#117 deliverable 2 — without the drain, a target the snapshot proves is gone keeps no closedAt, because the listener guard filters on delivery time and the destroy may never be observed.",
    file: "src/capture/targets.ts",
    find: "entry.closedAt === undefined && drainable.has(entry.targetId) && !live.has(entry.targetId),",
    replace: "false,",
    suite: "bun",
    expect: "closes a target the snapshot proves is gone",
  },
  {
    id: "snapshot-drain-ignores-inflight-creation",
    why: "#117 review — Target.getTargets is not atomic: Chromium enumerates, then the response travels back. Without restricting the drain to what was recorded before the request, a target created in that window is stamped closed while it is still alive.",
    file: "src/capture/targets.ts",
    find: "entry.closedAt === undefined && drainable.has(entry.targetId) && !live.has(entry.targetId),",
    replace: "entry.closedAt === undefined && !live.has(entry.targetId),",
    suite: "bun",
    expect: "does not close a target created while the snapshot was in flight",
  },
  {
    id: "archive-association-containment-unchecked",
    why: "#123 - checkpoints.json is data that names the other artifacts and arrives with the archive, so a reader that resolves an association without a containment check reopens the hole publication already closed, on every read.",
    file: "src/archive/read.ts",
    find: "if (!isStrictlyWithin(root, path)) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses an association that resolves outside the archive root",
  },
  {
    id: "capture-tool-leaks-the-browser",
    why: "#124 - without the finally, every capture_page call over a long-lived MCP session leaves a Chromium process behind. A unit test that only checks the return value passes either way.",
    file: "src/serve/tools/capture-page.ts",
    find: "await browser.close();",
    replace: "void browser;",
    suite: "bun",
    expect: "releases the browser after a successful capture",
  },
  {
    id: "capture-tool-returns-the-har-as-the-archive",
    why: "#124 - captureHar returns the HAR path, not the archive root. Returning it as the archive sends the caller straight into inspect_archive's 'not an archive' refusal.",
    file: "src/serve/tools/capture-page.ts",
    find: "return { archive: outDir, har, url: params.url };",
    replace: "return { archive: har, har, url: params.url };",
    suite: "bun",
    expect: "returns the archive directory, not the HAR path inside it",
  },
  {
    id: "mcp-swallows-a-tool-failure",
    why: "#124 - mapping a thrown tool error to a normal result would report a failed capture as a success to the agent. The layer-3 round trip is the only place this is visible.",
    file: "src/serve/mcp.ts",
    find: "            isError: true,",
    replace: "            isError: false,",
    suite: "bun",
    expect: "a failing tool comes back as an error result, not a dead connection",
  },
  {
    id: "capture-tool-writes-over-an-existing-path",
    why: "#127 - captureHar tolerates an existing empty directory, which is fine for a library call and destructive for a tool an agent drives: an empty user profile or mount point is an empty directory.",
    file: "src/serve/tools/capture-guards.ts",
    find: "if (exists(resolved)) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses an outDir that already exists",
  },
  {
    id: "capture-tool-reaches-the-private-network",
    why: "#127 - protocol-only validation let a caller reach loopback, cloud metadata and intranet hosts with the host's network position rather than its own.",
    file: "src/serve/tools/capture-guards.ts",
    find: "    if (kind !== undefined) {",
    replace: "    if (false) {",
    suite: "bun",
    expect: "refuses a URL that resolves to a private or loopback address",
  },
  {
    id: "replay-falls-through-to-the-live-network",
    why: "#133 - notFound: abort is what makes replay evidence rather than optimism. Fall through instead and an incomplete archive silently reaches the origin, so a replay of a broken archive looks perfect.",
    file: "src/replay/replay.ts",
    find: 'notFound: "abort", url: "**/*"',
    replace: 'notFound: "fallback", url: "**/*"',
    suite: "browser",
    expect: "refuses to reach a live origin for what the archive is missing",
  },
  {
    id: "inspector-grades-capture-fidelity-cases-as-animations",
    why: "#128 - the fixture manifest declares nine cases and only four are animations. Grading the carousel, the lazy asset and the cross-origin stylesheet as missing animations turns a complete archive into a page full of red.",
    file: "src/serve/inspector.ts",
    find: '.filter((entry) => entry.kind === "animation")',
    replace: ".filter(() => true)",
    suite: "bun",
    expect: "shows a gap as a row, not as a count nobody compared",
  },
  {
    id: "transcript-recorder-installed-too-late",
    why: "#114 - the recorder has to be installed after goto and BEFORE the sweep. Installed later it records none of the scrolling the sweep drives, and the transcript is an empty file that looks like a page which never moved.",
    file: "src/capture/record.ts",
    find: "      await page.evaluate(new Function(TRANSCRIPT_INIT_SCRIPT) as () => void);",
    replace: "      void TRANSCRIPT_INIT_SCRIPT;",
    suite: "browser",
    expect: "records the scrolling the adaptive sweep drove",
  },
  {
    id: "transcript-scroll-listener-outside-the-capture-phase",
    why: "#115/§6.11 - a scroll on a nested container does not bubble to window. Without the capture phase the listener records the page and reports nothing for an inner scroller, which is indistinguishable from a container that never moved. The fixture's nested-scroller declares that case.",
    file: "src/capture/transcript.ts",
    find: "  }, true);",
    replace: "  }, false);",
    suite: "browser",
    expect: "records a nested container that scrolls itself",
  },
  {
    id: "snapshot-merged-in-arrival-order",
    why: "#122 - Target.getTargets promises no ordering. Merging in arrival order loses an opener relationship whenever the browser lists a child before its parent, because appendDiscovered can only assert an opener this run already recorded.",
    file: "src/capture/targets.ts",
    find: "      if (waitingOnSnapshotOpener) {",
    replace: "      if (false) {",
    suite: "bun",
    expect: "keeps an opener relationship the snapshot happened to list out of order",
  },
  {
    id: "discovery-not-scoped-to-this-run",
    why: "#122 - Target.setDiscoverTargets is browser-wide. Without scoping to this run's browserContextId, a concurrent capture sharing the browser pours its targets into this inventory and the archive describes a page it never visited.",
    file: "src/capture/targets.ts",
    find: "  return info.browserContextId === runContextId;",
    replace: "  return true;",
    suite: "browser",
    expect: "does not report targets from a concurrent capture sharing the browser",
  },
  {
    id: "capture-tool-unbounded-concurrency",
    why: "#127 - an MCP server is long-lived and an agent can call a tool as often as it likes. Unbounded, every concurrent call launches its own Chromium and a handful is a host with no memory left - a failure that belongs to the machine, so nothing inspecting an archive would see it.",
    file: "src/serve/tools/capture-page.ts",
    find: "  const run = captureQueue.then(async () => {",
    replace: "  const run = Promise.resolve().then(async () => {",
    suite: "bun",
    expect: "never runs two browsers at once",
  },
  {
    id: "post-sweep-drain-unbounded",
    why: "#127 - the drain runs after the sweep and so outside §6.10's wall-clock budget. One script read that never answers holds a browser open, and through the MCP tool the caller's request with it. A drain outside the budget is a hole in the budget.",
    file: "src/capture/budget.ts",
    find: "        timer = setTimeout(() => resolve(false), deadlineMs);",
    replace: "        timer = setTimeout(() => resolve(false), 3_600_000);",
    suite: "bun",
    expect: "stops waiting on work that outlasts the deadline",
  },
  {
    id: "archive-reader-echoes-runtime-errors",
    why: "#127 - a raw parse or permission error carries the runtime's own account of the bytes and of what exists where, and it travels back over MCP to whoever is driving the tool. The caller supplied the path; it did not ask for the parser's phrasing.",
    file: "src/archive/read.ts",
    find: "    throw new Error(`inspect_archive: ${fileName} in ${root} is not readable as JSON`);",
    replace: "    throw error;",
    suite: "bun",
    expect: "fails with a stable message, not a raw parser error",
  },
  {
    id: "allowed-roots-not-enforced",
    why: "#127 - a restriction a deployment sets and the tool ignores is worse than none, because the operator believes it holds. The mechanism is only worth adding if it is enforced.",
    file: "src/serve/tools/inspect-archive.ts",
    find: "    if (!params.allowedRoots.some((root) => isWithin(resolve(root), wanted))) {",
    replace: "    if (false) {",
    suite: "bun",
    expect: "refuses an archive outside the allowed roots",
  },
  {
    id: "fingerprint-key-gates-on-ordinal-and-text",
    why: "Issue #20, fixed in 44e2671 — ordinal and text hash were equality components of the bucket key, so one node inserted above a target made an element with a unique stable attribute unmatchable. It was reported `missing` and `replayOnly` at once.",
    file: "src/identity/fingerprint.ts",
    find: 'return [el.frameKey, el.tag, attrs].join("|");',
    replace: 'return [el.frameKey, el.tag, attrs, el.siblingOrdinal, el.textHash ?? ""].join("|");',
    suite: "bun",
    expect: "one unrelated node inserted above does not lose an element with a unique attribute",
  },
  {
    id: "request-normalization-association-required",
    why: "Issue #86 — dropping the required requestNormalization run association from checkpoints validation let an archive without a policy pass the manifest guard.",
    file: "src/capture/checkpoints.ts",
    find: 'if (!isRunAssociation(checkpointsDocument.requestNormalization)) return { ok: false };',
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects a document missing the run-level request-normalization association",
  },
  {
    id: "request-normalization-staged-file-required",
    why: "Issue #86 — dropping the staged regular-file check let an archive publish a policy that escapes the root through a symlink while remaining valid JSON.",
    file: "src/capture/checkpoints.ts",
    find: '!(await isStagedRegularFile(stagingRoot, stagedDocument.requestNormalization as RunAssociation))',
    replace: "false",
    suite: "bun",
    expect: "refuses when request-normalization.json resolves outside the staging root",
  },
  {
    id: "request-normalization-schema-unchecked",
    why: "Issue #86 — dropping the policy schema validation let a malformed or non-empty-key policy be published.",
    file: "src/capture/checkpoints.ts",
    find: "if (requestNormalizationDoc === undefined || !validateRequestNormalization(requestNormalizationDoc).ok) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when request-normalization.json is invalid JSON",
  },
  {
    id: "request-normalization-producer-ambiguity-unchecked",
    why: "Issue #91 — dropping the producer-side ambiguity check let a capture publish an archive whose policy collapses two distinct requests into one normalized match.",
    file: "src/capture/record.ts",
    find: 'const ambiguous = findAmbiguousNormalizedRequests(harEntries, volatileKeys);',
    replace: "const ambiguous: string[] = [];",
    suite: "bun",
    expect: "captureHar refuses when the policy collapses two distinct archived requests",
  },
  {
    id: "request-normalization-staged-ambiguity-unchecked",
    why: "Issue #91 — dropping the staged re-check let a tampered policy collapse distinct archived requests bypass the producer guard.",
    file: "src/capture/checkpoints.ts",
    find: "if (findAmbiguousNormalizedRequests(harEntries, volatileKeys as string[]).length > 0) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when the policy collapses distinct archived requests (ambiguity)",
  },
  {
    id: "commit-association-required",
    why: "Issue #103 — dropping the required commit run association from checkpoints validation let an archive publish without a commit marker.",
    file: "src/capture/checkpoints.ts",
    find: 'if (!isRunAssociation(checkpointsDocument.commit)) return { ok: false };',
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects a document missing the run-level commit association",
  },
  {
    id: "commit-marker-not-written",
    why: "Issue #103 — dropping the commit write let a capture publish without a marker a reader could verify against.",
    file: "src/capture/record.ts",
    find: "const commit = await buildCommit(stagingRoot, finalCheckpoint.checkpointId);",
    replace: "const commit = { schemaVersion: 0, producer: { name: \"x\", version: \"0\" }, createdAt: 0, artifacts: [], checkpointId: \"\" };",
    suite: "bun",
    expect: "captureHar publishes a commit marker that verifies the archive bytes",
  },
  {
    id: "termination-association-required",
    why: "Issue #104 — dropping the required termination run association from checkpoints validation let an archive publish without recording why capture stopped.",
    file: "src/capture/checkpoints.ts",
    find: 'if (!isRunAssociation(checkpointsDocument.termination)) return { ok: false };',
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects a document missing the run-level termination association",
  },
  {
    id: "termination-not-recorded",
    why: "Issue #104 — dropping the termination write let a capture publish without a record of its outcome, making a truncated capture indistinguishable from a complete one.",
    file: "src/capture/record.ts",
    find: "const terminationDecision = evaluateBudget(sweepBudgets, terminationStats);",
    replace: "const terminationDecision = { stop: false } as const;",
    suite: "bun",
    expect: "captureHar records budget-exceeded when the wall-clock cap is crossed",
  },
  {
    id: "termination-staged-file-required",
    why: "Issue #104 follow-up — dropping the termination staged regular-file check let a capture publish an archive whose association names a missing or directory termination.json (it is written before validation, unlike commit, so it can and must be checked here).",
    file: "src/capture/checkpoints.ts",
    find: 'if (!(await isStagedRegularFile(stagingRoot, stagedDocument.termination as RunAssociation))) {',
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when termination.json is missing",
  },
  {
    id: "targets-association-required",
    why: "Issue #117 — removing the required run-level targets association accepted an archive that never indexed the inventory.",
    file: "src/capture/checkpoints.ts",
    find: "if (!isRunAssociation(checkpointsDocument.targets)) return { ok: false };",
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects a document missing the run-level targets association",
  },
  {
    id: "targets-containment-unchecked",
    why: "Issue #117 — removing the staged-file check let a targets association outside the staging root be read as this run's evidence.",
    file: "src/capture/checkpoints.ts",
    find: "if (!(await isStagedRegularFile(stagingRoot, stagedDocument.targets as RunAssociation))) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when the targets association resolves outside the staging root",
  },
  {
    id: "targets-document-validated",
    why: "Issue #117 — removing inventory validation accepted a malformed inventory and one whose target closed before it opened.",
    file: "src/capture/checkpoints.ts",
    find: "if (targetsDoc === undefined || !validateTargets(targetsDoc).ok) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses a target that closed before it opened",
  },
  {
    id: "storage-read-after-a-cross-origin-redirect",
    why: "#157 - storage is read from the page after navigation. When the page landed on a different origin those entries belong to that origin, and the allowlist was written for the requested one. Reading anyway publishes another origin's data under a label that is not its own - which is exactly what the whole-capture refusal this replaced existed to prevent.",
    file: "src/capture/environment.ts",
    find: "  const storageIsThisOrigin = primaryOrigin !== \"null\" && finalOrigin === primaryOrigin;",
    replace: "  const storageIsThisOrigin = primaryOrigin !== \"null\";",
    suite: "browser",
    expect: "publishes a capture that redirected cross-origin, without that origin's storage",
  },
  {
    id: "final-origin-escapes-the-address-policy",
    why: "#157 - the pre-flight address check only sees the URL the caller asked for. The refusal it used to be paired with is gone, so without this hook a public URL that redirects to 169.254.169.254 publishes the internal page to disk instead of being thrown away.",
    file: "src/capture/environment.ts",
    find: "    if (origin === primaryOrigin) continue;",
    replace: "    continue;",
    suite: "bun",
    expect: "capturePage refuses when a redirect lands on a private address",
  },
  {
    id: "capture-tool-supplies-a-permissive-origin-policy",
    why: "#157 - the guard in captureHar is only as good as the policy the tool hands it, and a reviewer pointed out the entry above cannot see that: emptying the callback leaves every anchor in src/capture intact. This is the other half - the tool keeps passing a policy, and the policy permits everything.",
    file: "src/serve/tools/capture-page.ts",
    find: "        await assertReachableUrl(origin, params.allowPrivateNetwork === true, params.resolveHost);",
    replace: "        void origin;",
    suite: "bun",
    expect: "capturePage refuses when a redirect lands on a private address",
  },
  {
    id: "outstanding-responses-do-not-affect-the-outcome",
    why: "#156 - three captures of labs.chaingpt.org reported complete/quiet-window while holding 5, 1 and 3 HAR entries with no response, one of them the jQuery the page's whole interaction layer needs. Without this, an archive missing what the page asked for is indistinguishable from one that has everything.",
    file: "src/capture/budget.ts",
    find: "  const outcome = naturalEnd && stats.unansweredRequests === 0 ? \"complete\" : \"incomplete\";",
    replace: "  const outcome = naturalEnd ? \"complete\" : \"incomplete\";",
    suite: "browser",
    expect: "does not report complete when a response was never received",
  },
  {
    id: "unanswered-requests-counted-by-a-falsy-status",
    why: "#156 - Playwright writes an unanswered request as status -1, which is truthy. Counting on falsiness reports zero for exactly the entries this exists to find.",
    file: "src/capture/record.ts",
    find: "      return typeof status !== \"number\" || status < 100;",
    replace: "      return !status;",
    suite: "browser",
    expect: "does not report complete when a response was never received",
  },
  {
    id: "an-outstanding-response-read-as-a-failure",
    why: "#156 - Playwright writes both a failed request and one still in flight at teardown with status -1, and only `_failureText` separates them. Reading every responseless entry as a failure empties the count that drives the outcome, so the archive defect this exists to report becomes invisible again.",
    file: "src/capture/record.ts",
    find: "      (response) => response?._failureText !== undefined,",
    replace: "      () => true,",
    suite: "browser",
    expect: "does not report complete when a response was never received",
  },
  {
    id: "unservable-entries-left-to-the-har-router",
    why: "#155 - routeFromHAR matches an entry with no response and then neither fulfils nor aborts, so the request hangs forever. Without this abort, five such entries on labs.chaingpt.org left DOMContentLoaded and load both unfired and every replay of that site timed out.",
    file: "src/replay/replay.ts",
    find: "  if (unservable.size > 0) {",
    replace: "  if (false) {",
    suite: "browser",
    expect: "does not stall on a HAR entry the archive has no response for",
  },
  {
    id: "unservable-detected-by-a-truthy-status",
    why: "#155 - Playwright writes an incomplete request as status -1, so a check for a falsy status misses it entirely. The sentinel is 'not a real HTTP status', not 'zero'.",
    file: "src/replay/replay.ts",
    find: "    (typeof status === \"number\" && status >= 100 ? servable : unservable).add(url);",
    replace: "    (status !== 0 ? servable : unservable).add(url);",
    suite: "browser",
    expect: "does not stall on a HAR entry the archive has no response for",
  },
  {
    id: "one-bad-entry-condemns-the-whole-url",
    why: "#155 - a HAR can hold a good GET and a still-open POST for one URL. Refusing the URL on the bad entry alone aborts an asset the archive can serve, which removes working motion from a replay that previously had it - a worse failure than the stall being fixed.",
    file: "src/replay/replay.ts",
    find: "  for (const url of servable) unservable.delete(url);",
    replace: "  void servable;",
    suite: "browser",
    expect: "still serves a URL the archive has a good entry for, alongside a bad one",
  },
  {
    id: "fallback-continues-to-the-live-network",
    why: "#155 - every request that is not unservable now passes through this handler. `continue()` sends it to the network instead of deferring to the HAR router, which breaks the guarantee the whole archive rests on and looks identical offline. Only a test with the origin still listening can tell the two apart.",
    file: "src/replay/replay.ts",
    find: "      await route.fallback();",
    replace: "      await (route as unknown as { continue(): Promise<void> }).continue();",
    suite: "browser",
    expect: "still refuses a live origin when the unservable handler is installed",
  },
  {
    id: "network-drain-not-awaited",
    why: "#156 second deliverable - without waiting for in-flight responses at the observation boundary, the context teardown turns them into HAR entries with no response. Measured on firecrawl.dev before this: 4 entries with no response and no recorded failure.",
    file: "src/capture/record.ts",
    find: "      networkDrainSettled = await networkDrain.idle(NETWORK_DRAIN_DEADLINE_MS);",
    replace: "      networkDrainSettled = networkDrain.inFlight() === 0;",
    suite: "browser",
    expect: "waits for a response that arrives after the sweep has ended",
  },
  {
    id: "network-drain-counts-only-completions",
    why: "#156 - a drain that never learns a request started is idle from the first instant and returns immediately, which looks exactly like a page with nothing outstanding. The failure is silent in every offline test.",
    file: "src/capture/record.ts",
    find: "      page.on(\"request\", () => networkDrain.started());",
    replace: "      page.on(\"request\", () => {});",
    suite: "browser",
    expect: "waits for a response that arrives after the sweep has ended",
  },
];
