export interface Mutation {
  id: string;
  why: string;
  file: string;
  find: string;
  replace: string;
  suite: "bun" | "browser";
  expect: string;
}

// Browser-only defects are deliberately not in this corpus yet: the page.url() epoch leak and
// the epoch:0 counter need suite: "browser" wiring that this pass does not exercise.
export const MUTATIONS: Mutation[] = [
  {
    id: "publish-validation-unwired",
    why: "2d29a66 — deleting the call left 47 Bun + 22 browser green.",
    file: "src/capture/record.ts",
    find: "if (!staged.ok) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "captureHar refuses to publish when a HAR attachment corrupts a staged sidecar",
  },
  {
    id: "epoch-shape-rule-gone",
    why: "Issue #47 — removing the document-epoch shape check let URL-shaped and short epochs pass.",
    file: "src/capture/checkpoints.ts",
    find: "^epoch:[0-9A-Za-z_-]{16,}$",
    replace: ".+",
    suite: "bun",
    expect: "rejects a documentEpoch that carries the captured page URL",
  },
  {
    id: "epoch-binding-unchecked",
    why: "89650be — deleting the documentEpoch binding refusal left 61 Bun tests green.",
    file: "src/capture/checkpoints.ts",
    find: "if (binding.documentEpoch !== finalCheckpoint.primaryTarget.documentEpoch) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when the binding names the final checkpoint but a different document epoch",
  },
  {
    id: "openedat-binding-unchecked",
    why: "1b71ef2 — deleting the openedAt binding refusal left 61 Bun tests green.",
    file: "src/capture/checkpoints.ts",
    find: "if (binding.openedAt !== finalCheckpoint.openedAt) return { ok: false };",
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "refuses when the binding names the final checkpoint but a different openedAt",
  },
  {
    id: "mid-checkpoint-navigation-allowed",
    why: "Issue #47 — deleting the loaderId change refusal allowed mid-checkpoint navigation.",
    file: "src/capture/record.ts",
    find: "if (loaderIdAtClose !== loaderIdAtOpen) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "captureHar refuses to publish when the primary document changes while the checkpoint was open",
  },
  {
    id: "har-existence-unchecked",
    why: "Issue #47 — removing the HAR isFile refusal allowed a directory association.",
    file: "src/capture/checkpoints.ts",
    find: "if (!(await lstat(path)).isFile()) return false;",
    replace: "if (false) return false;",
    suite: "bun",
    expect: "refuses when the HAR association names a directory",
  },
  {
    id: "har-containment-unchecked",
    why: "Issue #47 — removing the HAR containment refusal allowed an association outside staging.",
    file: "src/capture/checkpoints.ts",
    find: "return isStrictlyWithin(resolvedRoot, resolvedPath);",
    replace: "return true;",
    suite: "bun",
    expect: "refuses when the HAR association resolves outside the staging root",
  },
  {
    id: "capabilities-association-required",
    why: "Issue #63 — removing the required run-level capabilities association accepted an unindexed artifact.",
    file: "src/capture/checkpoints.ts",
    find: "if (!isRunAssociation(doc.capabilities)) return { ok: false };",
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects a document missing the run-level capabilities association",
  },
  {
    id: "capabilities-file-required",
    why: "Issue #63 — removing the capabilities staged-file check accepted a missing or non-file artifact.",
    file: "src/capture/checkpoints.ts",
    find: "if (!(await isStagedRegularFile(stagingRoot, checkpointsDoc.capabilities))) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when capabilities.json resolves outside the staging root",
  },
  {
    id: "capabilities-document-validated",
    why: "Issue #63 — removing capabilities document validation accepted invalid JSON and invalid schema documents.",
    file: "src/capture/checkpoints.ts",
    find: "if (capabilitiesDoc === undefined || !validateCapabilities(capabilitiesDoc).ok) {",
    replace: "if (false) {",
    suite: "bun",
    expect: "refuses when capabilities.json has an unsupported schema version",
  },
  {
    id: "capabilities-flag-values-validated",
    why: "Issue #63 — removing tri-state value validation accepted values outside the contract.",
    file: "src/capture/checkpoints.ts",
    find: "if (flag in doc.flags && !isCapabilityValue(doc.flags[flag])) return { ok: false };",
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects capabilities with a value outside the tri-state contract",
  },
  {
    id: "capabilities-flags-required",
    why: "Issue #63 — removing the required-flag check accepted incomplete capability evidence.",
    file: "src/capture/checkpoints.ts",
    find: "if (!(flag in doc.flags)) return { ok: false };",
    replace: "if (false) return { ok: false };",
    suite: "bun",
    expect: "rejects capabilities missing one of the four flags",
  },
  {
    id: "capability-service-worker-detection",
    why: "Issue #64 — suppressing the ServiceWorker registration observation made a true dependency look absent.",
    file: "src/capture/record.ts",
    find: "serviceWorkerDependent = true;",
    replace: "serviceWorkerDependent = false;",
    suite: "browser",
    expect: "publishes true capabilities for the capability fixture",
  },
  {
    id: "capability-websocket-detection",
    why: "Issue #64 — suppressing the live WebSocket observation made a refused socket look absent.",
    file: "src/capture/record.ts",
    find: "webSocketDependent = true;",
    replace: "webSocketDependent = false;",
    suite: "browser",
    expect: "publishes true capabilities for the capability fixture",
  },
  {
    id: "capability-closed-shadow-root-detection",
    why: "Issue #64 — replacing the pierced DOM result with false hid a closed shadow root.",
    file: "src/capture/record.ts",
    find: "const closedShadowRootPresent = hasClosedShadowRoot(domDocument.root);",
    replace: "const closedShadowRootPresent = false;",
    suite: "browser",
    expect: "publishes true capabilities for the capability fixture",
  },
  {
    id: "capability-sourcemap-detection",
    why: "Issue #64 — replacing sourcemap declaration detection with false hid declared maps.",
    file: "src/capture/record.ts",
    find: "sourcemapDeclared: discoveredMapUrls.size > 0 ? true : scriptBodyUnreadable ? \"undetermined\" : false,",
    replace: "sourcemapDeclared: false,",
    suite: "browser",
    expect: "publishes true capabilities for the capability fixture",
  },
];
